CREATE TABLE IF NOT EXISTS platform_tenant_topic_assignments (
  assignment_id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  tenant_id CHAR(36) NOT NULL,
  topic_skill_id VARCHAR(160) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'active' CHECK (status IN ('active','revoked')),
  assigned_by CHAR(36) NULL,
  assigned_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  expires_at DATETIME(6) NULL,
  revoked_by CHAR(36) NULL,
  revoked_at DATETIME(6) NULL,
  revoke_reason VARCHAR(500) NOT NULL DEFAULT '',
  CONSTRAINT fk_tenant_topic_assignment_tenant FOREIGN KEY (tenant_id) REFERENCES platform_tenants(tenant_id) ON DELETE CASCADE,
  CONSTRAINT fk_tenant_topic_assignment_actor FOREIGN KEY (assigned_by) REFERENCES platform_user_profiles(user_id) ON DELETE SET NULL,
  CONSTRAINT fk_tenant_topic_assignment_revoker FOREIGN KEY (revoked_by) REFERENCES platform_user_profiles(user_id) ON DELETE SET NULL,
  UNIQUE KEY uq_tenant_topic_assignment (tenant_id, topic_skill_id),
  KEY idx_tenant_topic_assignment_status (tenant_id, status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS platform_cross_tenant_resource_grants (
  grant_id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  source_tenant_id CHAR(36) NOT NULL,
  recipient_tenant_id CHAR(36) NOT NULL,
  resource_type VARCHAR(64) NOT NULL,
  resource_key VARCHAR(200) NOT NULL,
  actions JSON NOT NULL DEFAULT (JSON_ARRAY()),
  field_scope JSON NOT NULL DEFAULT (JSON_ARRAY()),
  schema_fingerprint CHAR(64) NOT NULL,
  purpose VARCHAR(500) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'active' CHECK (status IN ('active','revoked')),
  effective_at DATETIME(6) NOT NULL,
  expires_at DATETIME(6) NOT NULL,
  created_by CHAR(36) NULL,
  approved_by CHAR(36) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  revoked_by CHAR(36) NULL,
  revoked_at DATETIME(6) NULL,
  revoke_reason VARCHAR(500) NOT NULL DEFAULT '',
  CONSTRAINT chk_cross_tenant_grant_distinct CHECK (source_tenant_id <> recipient_tenant_id),
  CONSTRAINT chk_cross_tenant_grant_window CHECK (expires_at > effective_at),
  CONSTRAINT fk_cross_tenant_grant_source FOREIGN KEY (source_tenant_id) REFERENCES platform_tenants(tenant_id) ON DELETE CASCADE,
  CONSTRAINT fk_cross_tenant_grant_recipient FOREIGN KEY (recipient_tenant_id) REFERENCES platform_tenants(tenant_id) ON DELETE CASCADE,
  CONSTRAINT fk_cross_tenant_grant_creator FOREIGN KEY (created_by) REFERENCES platform_user_profiles(user_id) ON DELETE SET NULL,
  CONSTRAINT fk_cross_tenant_grant_approver FOREIGN KEY (approved_by) REFERENCES platform_user_profiles(user_id) ON DELETE SET NULL,
  CONSTRAINT fk_cross_tenant_grant_revoker FOREIGN KEY (revoked_by) REFERENCES platform_user_profiles(user_id) ON DELETE SET NULL,
  KEY idx_cross_tenant_grant_recipient (recipient_tenant_id, status, expires_at),
  KEY idx_cross_tenant_grant_resource (source_tenant_id, resource_type, resource_key, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
