from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from backend.platform.api.router import API_ROUTE_REGISTRY


OUTPUT = PROJECT_ROOT / "src/app/services/generatedApiClient.ts"


def render() -> str:
    routes = sorted(
        API_ROUTE_REGISTRY.list_routes(),
        key=lambda item: (str(item["path"]), str(item["method"])),
    )
    lines = [
        "// Generated by scripts/generate_api_client.py. Do not edit manually.",
        "export const generatedApiRoutes = {",
    ]
    for route in routes:
        operation_id = str(route["operation_id"])
        lines.append(
            f'  "{operation_id}": {{ method: "{route["method"]}", path: "{route["path"]}", authRequired: {str(bool(route["auth_required"])).lower()} }},'
        )
    lines.extend(
        [
            "} as const;",
            "",
            "export type GeneratedOperationId = keyof typeof generatedApiRoutes;",
            "export type GeneratedJsonObject = Record<string, unknown>;",
            "",
            "export async function callGeneratedApi<TResponse extends GeneratedJsonObject = GeneratedJsonObject>(",
            "  operationId: GeneratedOperationId,",
            "  options: { query?: URLSearchParams; body?: GeneratedJsonObject; signal?: AbortSignal } = {},",
            "): Promise<TResponse> {",
            "  const route = generatedApiRoutes[operationId];",
            "  const query = options.query?.toString();",
            "  const response = await fetch(`${route.path}${query ? `?${query}` : \"\"}`, {",
            "    method: route.method,",
            "    credentials: \"include\",",
            "    headers: options.body ? { \"Content-Type\": \"application/json\" } : undefined,",
            "    body: options.body ? JSON.stringify(options.body) : undefined,",
            "    signal: options.signal,",
            "  });",
            "  const payload = (await response.json().catch(() => ({}))) as GeneratedJsonObject;",
            "  if (!response.ok) throw Object.assign(new Error(String(payload.message || payload.error || `HTTP ${response.status}`)), { status: response.status, payload });",
            "  return payload as TResponse;",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            raise SystemExit("generated API client drift: run scripts/generate_api_client.py")
        return
    OUTPUT.write_text(expected, encoding="utf-8")


if __name__ == "__main__":
    main()
