from __future__ import annotations

from collections import Counter
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from backend.platform.database.schema_catalog import DEFERRED_FOREIGN_KEYS, TABLES, ColumnSpec, TableSpec, validate_catalog


DOCS_DIR = ROOT / "docs" / "database_tables"
POSTGRES_DDL = ROOT / "backend" / "platform" / "database" / "postgresql" / "0001_production_schema.sql"


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def column_ddl(column: ColumnSpec) -> str:
    if not column.name:
        return f"  {column.constraints}"
    suffix = f" {column.constraints}" if column.constraints else ""
    return f"  {column.name} {column.sql_type}{suffix}"


def create_table_ddl(table: TableSpec) -> str:
    columns = ",\n".join(column_ddl(column) for column in table.columns)
    statements = [f"CREATE TABLE {table.name} (\n{columns}\n);"]
    statements.append(f"COMMENT ON TABLE {table.name} IS {sql_literal(table.purpose)};")
    for column in table.columns:
        if column.name:
            statements.append(
                f"COMMENT ON COLUMN {table.name}.{column.name} IS {sql_literal(column.description)};"
            )
    for index in table.indexes:
        unique = "UNIQUE " if index.unique else ""
        where = f" WHERE {index.where}" if index.where else ""
        statements.append(
            f"CREATE {unique}INDEX {index.name} ON {table.name} ({', '.join(index.columns)}){where};"
        )
    return "\n".join(statements)


def generate_postgres_ddl() -> str:
    validate_catalog()
    sections = [
        "-- Generated by scripts/generate_database_schema.py. Do not edit by hand.",
        "-- PostgreSQL is the production source of truth; SQLite remains a local-development adapter.",
        "CREATE EXTENSION IF NOT EXISTS pgcrypto;",
    ]
    ordered_tables = _dependency_ordered_tables()
    sections.extend(create_table_ddl(table) for table in ordered_tables)
    for table, constraint, column, reference, on_delete in DEFERRED_FOREIGN_KEYS:
        sections.append(
            f"ALTER TABLE {table} ADD CONSTRAINT {constraint} "
            f"FOREIGN KEY ({column}) REFERENCES {reference} ON DELETE {on_delete};"
        )
    return "\n\n".join(sections) + "\n"


def _dependency_ordered_tables() -> list[TableSpec]:
    """Stable topological order for inline foreign keys.

    The catalog is organized by business domain rather than DDL dependency.
    Deferred foreign keys deliberately break the few real cycles; every other
    referenced table must be emitted before its dependent table.
    """

    by_name = {table.name: table for table in TABLES}
    position = {table.name: index for index, table in enumerate(TABLES)}
    deferred = {(table, column) for table, _, column, _, _ in DEFERRED_FOREIGN_KEYS}
    dependencies: dict[str, set[str]] = {table.name: set() for table in TABLES}
    for table in TABLES:
        for column in table.columns:
            if (table.name, column.name) in deferred:
                continue
            for reference in re.findall(r"\bREFERENCES\s+([A-Za-z_][A-Za-z0-9_]*)", column.constraints, re.IGNORECASE):
                if reference in by_name and reference != table.name:
                    dependencies[table.name].add(reference)
    ordered: list[TableSpec] = []
    remaining = set(by_name)
    while remaining:
        ready = sorted(
            (name for name in remaining if not (dependencies[name] & remaining)),
            key=position.__getitem__,
        )
        if not ready:
            cycle = ",".join(sorted(remaining, key=position.__getitem__))
            raise ValueError(f"Production schema has an undeferred foreign-key cycle: {cycle}")
        for name in ready:
            ordered.append(by_name[name])
            remaining.remove(name)
    return ordered


def table_markdown(table: TableSpec) -> str:
    rows = [
        f"# `{table.name}`",
        "",
        f"- 领域：{table.domain}",
        f"- 用途：{table.purpose}",
        "- 生产数据库：PostgreSQL",
        "",
        "## 字段结构",
        "",
        "| 字段 | 类型 | 约束 | 说明 |",
        "|---|---|---|---|",
    ]
    for column in table.columns:
        if column.name:
            rows.append(
                f"| `{column.name}` | `{column.sql_type}` | {column.constraints or '无'} | {column.description} |"
            )
        else:
            rows.append(f"| 表级约束 | — | `{column.constraints}` | {column.description} |")
    rows.extend(["", "## 索引", ""])
    if table.indexes:
        rows.extend(
            f"- `{'UNIQUE ' if index.unique else ''}{index.name} ({', '.join(index.columns)})`"
            + (f" WHERE {index.where}" if index.where else "")
            for index in table.indexes
        )
    else:
        rows.append("- 主键索引；暂无额外索引。")
    deferred = [item for item in DEFERRED_FOREIGN_KEYS if item[0] == table.name]
    if deferred:
        rows.extend(["", "## 延后建立的外键", ""])
        rows.extend(
            f"- `{constraint}`：`{column}` → `{reference}`，删除策略 `{on_delete}`。"
            for _, constraint, column, reference, on_delete in deferred
        )
    if table.notes:
        rows.extend(["", "## 设计说明", ""])
        rows.extend(f"- {note}" for note in table.notes)
    rows.extend(
        [
            "",
            "## 结构来源",
            "",
            "本文件由 `backend/platform/database/schema_catalog.py` 自动生成；修改表结构时先修改 catalog，再重新生成 DDL 和文档。",
            "",
        ]
    )
    return "\n".join(rows)


def generate_readme() -> str:
    counts = Counter(table.domain for table in TABLES)
    rows = [
        "# Smart Data Agent 数据库逐表设计",
        "",
        f"目标生产模型共 **{len(TABLES)} 张表**。表数量由业务边界和可追溯性决定，与用户数并非线性关系；约 100 人规模仍采用模块化单体和同一 PostgreSQL 集群。",
        "",
        "SQLite 仅用于本地开发和测试；生产 DDL 位于 `backend/platform/database/postgresql/0001_production_schema.sql`。每张表均有独立 Markdown，且与 DDL 由同一 schema catalog 生成。",
        "",
        "## 领域统计",
        "",
        "| 领域 | 表数 |",
        "|---|---:|",
    ]
    rows.extend(f"| {domain} | {count} |" for domain, count in sorted(counts.items()))
    rows.extend(["", "## 逐表目录", ""])
    for domain in sorted(counts):
        rows.extend([f"### {domain}", ""])
        rows.extend(
            f"- [`{table.name}`](./{table.name}.md)：{table.purpose}"
            for table in TABLES
            if table.domain == domain
        )
        rows.append("")
    rows.extend(
        [
            "## 生成与漂移检查",
            "",
            "```bash",
            "python3 scripts/generate_database_schema.py --check",
            "python3 scripts/generate_database_schema.py --write",
            "```",
            "",
            "`--check` 用于 CI，任何手工修改生成文件或漏生成逐表文档都会失败。",
            "",
        ]
    )
    return "\n".join(rows)


def expected_files() -> dict[Path, str]:
    files = {POSTGRES_DDL: generate_postgres_ddl(), DOCS_DIR / "README.md": generate_readme()}
    files.update({DOCS_DIR / f"{table.name}.md": table_markdown(table) for table in TABLES})
    return files


def write_files() -> None:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    POSTGRES_DDL.parent.mkdir(parents=True, exist_ok=True)
    expected = expected_files()
    expected_paths = set(expected)
    for stale in DOCS_DIR.glob("*.md"):
        if stale not in expected_paths:
            stale.unlink()
    for path, content in expected.items():
        path.write_text(content, encoding="utf-8")


def check_files() -> None:
    drift = []
    for path, content in expected_files().items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            drift.append(str(path.relative_to(ROOT)))
    if drift:
        raise SystemExit("Generated database files are missing or stale:\n- " + "\n- ".join(drift))
    actual_docs = {path for path in DOCS_DIR.glob("*.md") if path.name != "README.md"}
    expected_docs = {DOCS_DIR / f"{table.name}.md" for table in TABLES}
    if actual_docs != expected_docs:
        raise SystemExit(f"Database table documentation set does not match the {len(TABLES)}-table catalog")


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write_files()
    else:
        check_files()


if __name__ == "__main__":
    main()
